[[plugin]]
repo = "adv-inn/Deckify"
exec_files = ["bin/librespot"]

[[plugin]]
repo = "mubaraknumann/unifideck"
# force_version = "Dev-20260812-215318-e24d3ab"
allow_prerelease = true

[[plugin]]
repo = "DeckSettings/decky-game-settings"

[[plugin]]
repo = "jurassicplayer/decky-autoflatpaks"