name: Build Custom Decky Store

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install requests

      - name: Generate Custom Store & Patch Plugins
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RAW_URL: https://raw.githubusercontent.com/${{ github.repository }}/store
        run: python build_store.py

      - name: Deploy to 'store' branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: store
          publish_dir: ./dist
          commit_message: "Auto-update store [skip ci]"