name: Build Custom Decky Store

on:
  schedule:
    - cron: '0 */6 * * *'   # Run every 6 hours
  workflow_dispatch:        # Allows manual triggering
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  build-and-deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install requests

      - name: Generate Custom Store & Patch Plugins
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Automatically build the URL for your store
          PAGES_URL: https://decky.lukemech.org
        run: python build_store.py

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5